### ISSUE TITLE
Integration : DeepSource

### ISSUE THREAD

**Issue by ankitdobhal** [pashmaklang/pashmak#106]
@parsampsh  I would like to share the steps to activate the [DeepSource](https://deepsource.io/) analysis on the repo. Activating analysis will help you to continuously analyze repo for code quality issues and fix commonly occurring issues using the auto-fix feature. 
- Using DeepSource to continuously analyze your repository:
- Install DeepSource on your repository [here](https://deepsource.io/signup).
- create .deepsource.toml configuration which you can use to configure your analysis settings.
- Activate analysis [here](https://deepsource.io/gh/pashmaklang/pashmak).

**Comment by ankitdobhal** [comment]
Update: PR #104  merged the configuration file in this repository. You just need to signup and install DeepSource to continuously analyze the repo.

**Comment by parsampsh** [comment]
Hello @ankitdobhal 
I wanted to do this yesterday but looks your service sanctioned my country(iran).
