### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Paptoos** [pashmaklang/pashmak#11]
pashmak have any logo ?

**Comment by parsampsh** [comment]
Hello. No. have you any idea?

**Comment by sami2020pro** [comment]
I think Pashmak does not have a logo and if **parsampsh** wants, I will design several logos and choose _one_.

**Comment by parsampsh** [comment]
> I think Pashmak does not have a logo and if **parsampsh** wants, I will design several logos and choose _one_.

This is perfect sami!

**Comment by Paptoos** [comment]
If logo designed , I can add it to icon packs for text editors

**Comment by sami2020pro** [comment]
OK

**Comment by parsampsh** [comment]
Thanks guys :)

**Comment by sami2020pro** [comment]
I create a simple logo but im not a **advance designer**.
Click [here](https://photos.google.com/search/_tra_/photo/AF1QipNj2qdXC_Evc_ItNUDi0TFtwjyAqUxPrQL_8Ajg) to see more.

**Comment by Paptoos** [comment]
The link is wrong

**Comment by parsampsh** [comment]
Yes. link is wrong

**Comment by sami2020pro** [comment]
How can i send image for you ?

**Comment by parsampsh** [comment]
> How can i send image for you ?

Cat you attach the image file in here?

**Comment by parsampsh** [comment]
Or you can send it to parsampsh@gmail.com

**Comment by sami2020pro** [comment]
OK, I send the image :) (maybe i send later)

**Comment by parsampsh** [comment]
@sami2020pro did you make it? if this is canceled, we can close issue.

**Comment by sami2020pro** [comment]
I made it (one), but I have no good idea if you can give me an idea ?!

**Comment by parsampsh** [comment]
> I made it (one), but I have no good idea if you can give me an idea ?!

so, actually i haven't idea to :) @Paptoos have you any idea?

**Comment by Paptoos** [comment]
I think about that

**Comment by parsampsh** [comment]
What about **A furry cat**? :)

**Comment by sami2020pro** [comment]
Wait 🔢

**Comment by mehanalavimajd** [comment]
I need a logo for creating www.pashmaklang.github.io
So please make it faster

**Comment by sami2020pro** [comment]
The subject of the logo is over (*-*) :success:

**Comment by sami2020pro** [comment]
> The subject of the logo is over (_-_) :safety_pin:

**Comment by parsampsh** [comment]
i added this to readme. https://github.com/pashmaklang/pashmak/tree/add-logo

**Comment by sami2020pro** [comment]
> i added this to readme. https://github.com/pashmaklang/pashmak/tree/add-logo

I suggest you convert the logo to **SVG** and keep the alpha channel seeded or **no bg** and modify color and resize it for other tasks, this is my idea.

**Comment by parsampsh** [comment]
Yes. i converted it. now i replace the new file.

**Comment by sami2020pro** [comment]
Now please change **Organization** logo.

**Comment by parsampsh** [comment]
Yes. i do this now.

**Comment by parsampsh** [comment]
Added. I'll close this issue.
