### ISSUE TITLE
Compiled Language

### ISSUE THREAD

**Issue by hasan-kashi** [pashmaklang/pashmak#125]
Hi ,you can convert pashmak from a interpreted language to a compiled language ,isn't this better?pashmak is very slow but you can write a llvm front end for pashmak and write pashmak in pashmak.

**Comment by parsampsh** [comment]
> Hi ,you can convert pashmak from a interpreted language to a compiled language ,isn't this better?pashmak is very slow but you can write a llvm front end for pashmak and write pashmak in pashmak.

Hi. Pashmak is inherently interpretive. We can't port it to a compiled programming language.
Maybe we can write a third party compiler for it. This compiler may speed up the program.
