### ISSUE TITLE
GUI Library

### ISSUE THREAD

**Issue by hasan-kashi** [pashmaklang/pashmak#126]
Hi,is there a gui library for pashmak ?

**Comment by sami2020pro** [comment]
Hello ✋
Unfortunately, nothing at the moment 😢
We need base libraries first (like os libs), then window systems libraries (like X11) and then high level libraries (like gtk)

**Comment by parsampsh** [comment]
Also, i need to think about a structure for multi threading for Pashmak. (currently Pashmak haven't multi threading).
