### ISSUE TITLE
New feature for Pashmak programming language (structs)

### ISSUE THREAD

**Issue by sami2020pro** [pashmaklang/pashmak#13]
Pashmak is a language that can **progress** but it must be **stronger**. (Global use and other)
I think we need **structures** in _Pashmak_ language.
This good **feature** for start and we can use structures for **many projects**.

for example (syntax):
```html
struct Person: first_name last_name age 

$name = Person
$name.first_name = 'Sami'
$name.last_name = 'Ghasemi'
$name.age = 14
```
(or we can use other **syntax**)

```html
type struct Person: first_name last_name age 

$name = Person 
$name.first_name = 'Sami'
$name.last_name = 'Ghasemi'
$name.age = 14
```

**Comment by parsampsh** [comment]
Hello. yes this is good idea. i think this syntax is better:

```bash
struct Person
       $first_name
       $last_name = 'some default value'
       $age
endstruct

$a = ^ new Person
# also we can use
$a; new Person; copy $a

$a.first_name = '...'


```

i will create a feature branch and work on this.

**Comment by sami2020pro** [comment]
Yes this good for **START** 
This syntax is very like _Ruby_:
```ruby 
x = 1
if x > 2
   puts "x is greater than 2"
elsif x <= 2 and x!=0
   puts "x is 1"
else
   puts "I can't guess the number"
end
```

**Comment by parsampsh** [comment]
ok :). i'll work on that.

**Comment by parsampsh** [comment]
i'm working on this feature in this branch https://github.com/parsampsh/pashmak/tree/feature/create-struct-system

**Comment by Paptoos** [comment]
I think structs can be a var type
like this :
```
$Person = struct {
    &name = "Your Name"
    &family
    &age
$amir = new $Person
$amir&name = 'Amir'
$amir&family = 'Ghazi'
$amir&age = 12
print $Perosn
```
My idea is :
structs can be have new type in pashmak programming language . 
And later can be like json , xml and other ...
It is should be have a sign like others 
xml have tags and json have {}
I selct & for this but you can change it
thanks

**Comment by parsampsh** [comment]
> I think structs can be a var type
> like this :
> 
> ```
> $Person = struct {
>     &name = "Your Name"
>     &family
>     &age
> $amir = new $Person
> $amir&name = 'Amir'
> $amir&family = 'Ghazi'
> $amir&age = 12
> print $Perosn
> ```
> 
> My idea is :
> structs can be have new type in pashmak programming language .
> And later can be like json , xml and other ...
> It is should be have a sign like others
> xml have tags and json have {}
> I selct & for this but you can change it
> thanks

don't worry :) i created something like that in the feature branch. maybe i merge it into master tomorrow.

**Comment by Paptoos** [comment]
Thanks , what is sign for this ?
how to create a structs  on this ?

**Comment by parsampsh** [comment]
read the doc: https://github.com/parsampsh/pashmak/tree/feature/create-struct-system#Structs

**Comment by sami2020pro** [comment]
> I think structs can be a var type
> like this :
> 
> ```
> $Person = struct {
>     &name = "Your Name"
>     &family
>     &age
> $amir = new $Person
> $amir&name = 'Amir'
> $amir&family = 'Ghazi'
> $amir&age = 12
> print $Perosn
> ```
> 
> My idea is :
> structs can be have new type in pashmak programming language .
> And later can be like json , xml and other ...
> It is should be have a sign like others
> xml have tags and json have {}
> I selct & for this but you can change it
> thanks

This is very like Go programming language !

**Comment by parsampsh** [comment]
so, actually syntax of the pashma is different :)

**Comment by sami2020pro** [comment]
Yes, I see 😂

**Comment by Paptoos** [comment]
I do not use go , But later we can create api with pashmak and we can use a pashmak just type , if api creates , i can create a libary for support this type of varibiles in python

**Comment by parsampsh** [comment]
guys, what is your say about creating an organization for pashmak in github? i think this have not much repos and don't needs to organization. but what is your say?

**Comment by Paptoos** [comment]
I think need

**Comment by parsampsh** [comment]
which name is good? `pashmaklang`?

**Comment by Paptoos** [comment]
not bad
i think return json is not good , we can create a datatype only for pashmak

**Comment by sami2020pro** [comment]
> guys, what is your say about creating an organization for pashmak in github? i think this have not much repos and don't needs to organization. but what is your say?

If we can make pashmak like Rust, Python, Go and other popular programming language we need to create to organisation account for Pashmak

**Comment by parsampsh** [comment]
so, i created it in https://github.com/pashmaklang

**Comment by parsampsh** [comment]
i'll transfer repo to that and invite you

**Comment by sami2020pro** [comment]
> so, i created it in https://github.com/pashmaklang

This very like Rust but we can create simple name: pashmak

**Comment by parsampsh** [comment]
> > so, i created it in https://github.com/pashmaklang
> 
> This very like Rust but we can create simple name: pashmak

this name is reserved

**Comment by sami2020pro** [comment]
OK

**Comment by parsampsh** [comment]
we can contact github and request to free that username for us later :). for now, we can work on this :)

**Comment by Paptoos** [comment]
please move this repo to it

**Comment by parsampsh** [comment]
yes i do this now.

**Comment by sami2020pro** [comment]
Nice

**Comment by parsampsh** [comment]
:)

**Comment by Paptoos** [comment]
Thanks

**Comment by parsampsh** [comment]
please join :)

**Comment by parsampsh** [comment]
guys, i want to merge the branch into the master. but there is an question. what is the next release number?
we have two options:
- `0.5.4` -> `0.6` : structs created

or make more changes and bugfixes and migrate to `1.0`.

what is your say?

**Comment by Paptoos** [comment]
i join 1 or 2 muintes later

**Comment by sami2020pro** [comment]
> guys, i want to merge the branch into the master. but there is an question. what is the next release number?
> we have two options:
> - `0.5.4` -> `0.6` : structs created
> 
> or make more changes and bugfixes and migrate to `1.0`.
> 
> what is your say?

0.5.8 is good

**Comment by parsampsh** [comment]
> > guys, i want to merge the branch into the master. but there is an question. what is the next release number?
> > we have two options:
> > 
> > * `0.5.4` -> `0.6` : structs created
> > 
> > or make more changes and bugfixes and migrate to `1.0`.
> > what is your say?
> 
> 0.5.8 is good

for semver, i think `0.6` is better. (struct is not a small feature (: )

**Comment by Paptoos** [comment]
> guys, i want to merge the branch into the master. but there is an question. what is the next release number?
> we have two options:
> 
> * `0.5.4` -> `0.6` : structs created
> 
> or make more changes and bugfixes and migrate to `1.0`.
> 
> what is your say?

0.6.0
or 
0.5.5
do not fast change version.

**Comment by Paptoos** [comment]
but 1.0 is not very good , because it is for stable version and we must go 0.11 if pashmak is not stable and we in 0.10 .

**Comment by parsampsh** [comment]
> but 1.0 is not very good , because it is for stable version and we must go 0.11 if pashmak is not stable and we in 0.10 .

yes right. i'll release `0.6`. but not tonight. we have to test it more.

**Comment by parsampsh** [comment]
i close this issue. please let's talk about #14
