### ISSUE TITLE
Using nuitka compiler instead of Pyinstaller

### ISSUE THREAD

**Issue by parsampsh** [pashmaklang/pashmak#130]
Have you any opinion about migrating to `nuitka` (https://nuitka.net) compiler instead of pyinstaller?

**Comment by mehanalavimajd** [comment]
Is it better than pyinstaller?

**Comment by parsampsh** [comment]
> Is it better than pyinstaller?

the strategy of this compiler is different than pyinstaller. this makes a very very small optimization in the speed of interpreter (very small). but the compiling time is very long and also installing that needs more requirements installed on the system,

**Comment by mehanalavimajd** [comment]
I think it's unnecessary and it will make the comipiling spedd time low.
