### ISSUE TITLE
Adding pashmak test to github actions

### ISSUE THREAD

**Issue by mehanalavimajd** [pashmaklang/pashmak#131]
We can feel the we need to have a test (CI)for our pashmak projects. 
There are a lot of tests like (node.js test , php test and ...) so we need a CI for pashmak in github.
You can create the test and send a PR to actions/ci.

**Comment by parsampsh** [comment]
> We can feel the we need to have a test (CI)for our pashmak projects.
> There are a lot of tests like (node.js test , php test and ...) so we need a CI for pashmak in github.
> You can create the test and send a PR to actions/ci.

We have it at https://github.com/pashmaklang/setup-pashmak

**Comment by mehanalavimajd** [comment]
I would create a pull request and send it to actions/ci
