### ISSUE TITLE
OS std library 

### ISSUE THREAD

**Issue by sami2020pro** [pashmaklang/pashmak#14]
I have one question, Pashmak language have one **OS standard library** ?

**Comment by parsampsh** [comment]
no. but will be created :)

**Comment by sami2020pro** [comment]
Nice, I **wait** for this std library ;)

**Comment by parsampsh** [comment]
what is your say about order of creating **OS library** and **structs**
i want to start one of them. which is good for first?

**Comment by sami2020pro** [comment]
**structs** is better for first, We need **structs** for build better.

**Comment by Paptoos** [comment]
use os in python

**Comment by parsampsh** [comment]
> use os in python

yes. we just need to write a internal module to be a interface for python os :)

**Comment by Paptoos** [comment]
we can not create a lot of libraries for pashmak
but if we can use python libraries in pashmak do not need create a lot of .
it can a great future

**Comment by parsampsh** [comment]
> we can not create a lot of libraries for pashmak
> but if we can use python libraries in pashmak do not need create a lot of .
> it can a great future

yes of course. for example `hash` module is a alias for python hashlib :)

**Comment by Paptoos** [comment]
no , we can import python libraries  with out create interface for it

**Comment by parsampsh** [comment]
> no , we can import python libraries with out create interface for it

oh. so i don't know. but this is hard to handle all of them in pashmak and maybe have conflict. actually, there is not good way for importing directly python modules.

**Comment by parsampsh** [comment]
also we already can use `os` in our code:

```bash
println os.getcwd() # or anything else
```

**Comment by parsampsh** [comment]
i think this is enough. @Paptoos is right. we create interface for all of python standard modules.

**Comment by parsampsh** [comment]
we can make them accessible from pashmak.

**Comment by Paptoos** [comment]
yes

**Comment by parsampsh** [comment]
so. can us close this issue? @sami2020pro what is your say about it?
also i have new idea for structs: create Inheritance system for structs

**Comment by sami2020pro** [comment]
> use os in python

We need to build this for pashmak

**Comment by sami2020pro** [comment]
> so. can us close this issue? @sami2020pro what is your say about it?
> also i have new idea for structs: create Inheritance system for structs

idk
It's still not clear what we want
Please wait

**Comment by sami2020pro** [comment]
> also we already can use `os` in our code:
> 
> ```bash
> println os.getcwd() # or anything else
> ```
> 

If we want to bootstrapping this language we dosent need Python

**Comment by sami2020pro** [comment]
> so. can us close this issue? @sami2020pro what is your say about it?
> also i have new idea for structs: create Inheritance system for structs

Close this issue, I complete the libraries standard later.

**Comment by parsampsh** [comment]
> > also we already can use `os` in our code:
> > ```shell
> > println os.getcwd() # or anything else
> > ```
> 
> If we want to bootstrapping this language we dosent need Python

so i think we cannot bootstrap this language. always we have dependency to the python. i think this is not a good idea.
