### ISSUE TITLE
Control flow in Pashmak programming language

### ISSUE THREAD

**Issue by sami2020pro** [pashmaklang/pashmak#15]
Does Pashmak support **conditional expressions** ?
If answer is **NO**, We need to write a simple conditional expressions like that (or Pashmak have hard to write control flow)
```html
if $num == 1
    print 'num equal 1'
else 
    print 'num not equal 1'
```

**Comment by parsampsh** [comment]
so, yes this is needed. also we can make it with the **sections** but this syntax is better.

we have to create this system based on the sections. i'll think about it.

**Comment by sami2020pro** [comment]
I and others need this **feature** !
I wanted to write a library for the **strings** and add it as a **standard library** to Pashmak, but I had this _problem_.
Please **FIX** this.

**Comment by Paptoos** [comment]
Hello
I think create conditional expressions is easy in python . 
but the functions must support return true or false and we have true or false operators like == or === or !=

**Comment by parsampsh** [comment]
> Hello
> I think create conditional expressions is easy in python .
> but the functions must support return true or false and we have true or false operators like == or === or !=

they have :)
actually all of python `eval` features can be used in pashmak :)

for example:

```bash
mem 2 == 2; gotoif condition_is_true
goto after_if
section condition_is_true
    println 'yes, 2 equals 2'
section after_if
```

**Comment by parsampsh** [comment]
this is in progress in [this branch](https://github.com/pashmaklang/pashmak/tree/feature/create-if-elif-endif-flow).

the code is ok, some bugfixes and tests and documentation is in progress.

**Comment by parsampsh** [comment]
0.6-alpha3 release.
