### ISSUE TITLE
Adding Generic To Pashmak

### ISSUE THREAD

**Issue by PooiaFerdowsi** [pashmaklang/pashmak#150]
we can add the generic to the pashmak

class Person<string>
         func HiGeneric()

        endfunc
endclass

but I don't know about generic & I don't know how to add it

**Comment by parsampsh** [comment]
You are comparing a dynamic type language with the static type languages :)
Generic system is not needed In the dynamic type languages :)

**Comment by PooiaFerdowsi** [comment]
but python use of typing library
