### ISSUE TITLE
replace `end*` with `end` for closing blocks

### ISSUE THREAD

**Issue by PooiaFerdowsi** [pashmaklang/pashmak#151]
I am learning lua in Lua upside down pashmak for end the function loop and others you use of end but in pashmak you must use of endclass endfunc and others 
THIS MEAN MORE KEYWORD AND LANGUAGE IS HARDER

now we can do it ?

**Comment by parsampsh** [comment]
Pashmak have not `end` keyword. This is for writing cleaner codes.
For a complicated nested statements, its better:
```bash
if something
    while true
        if other
            func hi()
            end
        end
    end
end

# this is better because we know that each end is for which block
if something
    while true
        if other
            func hi()
            endfunc
        endif
    endwhile
endif
```

**Comment by PooiaFerdowsi** [comment]
Yes . ***BUT BEGINNER DON'T SEE WHATS KEYWORDS* they say Pashmak with example 50 keywords is baddest of python/c with 30 keywords while pashmak only have example 25 keyword & such as next note implement of endif endwhile is one of thing that slow pashmak  !! 

clean codes , Yes Yes 
but you are not forces that forced developers , developers write clean code no developer's language !!!

this mean developers write following code

```python
func hi()
end

event = 0

if something
   event = 1
end

while True
      if event and other
          hi()
      end
end
```

developers write clean codes no their language !!!

**Comment by parsampsh** [comment]
Yes. the best idea is keep both of them. :)
i'll keep this issue. maybe we add this feature in the next update :)

**Comment by mehanalavimajd** [comment]
Yes I think we can have both of them

**Comment by mehanalavimajd** [comment]
Hi??? 
no end keyword?

**Comment by parsampsh** [comment]
> Hi??? no end keyword?

Not yet :)

**Comment by parsampsh** [comment]
PR #171 Adds this feature. I close this issue.

**Comment by mehanalavimajd** [comment]
Horray!
