### ISSUE TITLE
transcompiler

### ISSUE THREAD

**Issue by PooiaFerdowsi** [pashmaklang/pashmak#152]
I read a Discussion named Compiler But We Don't Know Anything In The Assembly & Binary Files Or Executable Files . Yes ?

but each one of we know at least two programming language and we can create a source-to-source
compiler like java script Babel .

See following code to Pashmak that translated to Lua , C , Python , C++ , Java & etc

println 'Hello , World'
C:
#include <stdio.h>
void main(){
printf("Hello , World")
}
C++:
#include
int main(){
std::cout << "Hello , World!";
}
Lua:
io.write("Hello , World!")
Python:
print ("Hello , World")
Java:
public class FileName {
public static void main(String arguments[]){
System.out.println("Hello , World");
}
}

PLEASE READ THIS COMMENT FULL
I AM SORRY FOR HIGH LENGTH
but we don't can use of a language like Java because this don't have goto and bock
but we can use of Java if we replace goto labels with another thing

**Comment by parsampsh** [comment]
Hello. Pashmak has some features that they are not available in other languages.
First, pashmak datatypes are handled in the python. but we haven't python's datatype features in other languages!
Second, pashmak has something like namespace, name define registry, shutdown event system, label and goto, and more...
This means we cannot convert it to anything else of Python.
But the next problem is about converting Pashmak to Python. This is not usable to convert a interpretive language to another interpretive language :)
So, we can't do this.

**Comment by PooiaFerdowsi** [comment]
Yes but Python implement pashmak language features by Library !!!!!!
python have PyPy , Lua have LuaJIT , C have gcc & cmake 
and pashmak will be have
Pashmak
TransPashmak ( or any name )

This means we cannot convert it to anything else of Python. ?
No , languages like C++ ( no C ) have all python feature & pashmak features only require list Pashmak
feature & find languages contain them . Yes?

also any interpreter language is simpler than compiler ( for create ) but they in speed are impossible to believe when we compare compiler language ( also Java is not compiler & is a transcompiler translate to VM code & Jvm is only an interpreter

Yes Hello , World is not good for big codes but only required list !!

**Comment by PooiaFerdowsi** [comment]
sorry for bad description

**Comment by parsampsh** [comment]
You are telling C++ has all of the python features :)
This means we should include all of the python c++ source code in our output c++ code? :)

**Comment by parsampsh** [comment]
Do you know how PyInstaller works? actually, this mixes the python code and injects it to the python interpreter binary.
And does not converts it to any other language. because python is created to have very more features than c++ that based on the c++. converting it directly to other languages like c++ is impossible. :)
and in technical facts, its not really good. i'll close this issue.
