### ISSUE TITLE
Low speed

### ISSUE THREAD

**Issue by mehanalavimajd** [pashmaklang/pashmak#159]
Python is slow , and so the programming language that is created with it is very slow 🐌 . So if we could switch to c/c++ or go or anything fast , it would be better.

**Comment by parsampsh** [comment]
I didn't work with each one of those languages you told. and also Pashmak is really depended to the Python interpreter.
Eval syntax, datatypes, and lot of other features are handled by Python.
So, the answer is NO. we can't port this interpreter to another language.
Also this takes a lot of time.
Shall i close this issue?
