### ISSUE TITLE
create inheritance system for structs

### ISSUE THREAD

**Issue by parsampsh** [pashmaklang/pashmak#17]
we need to create inheritance system for structs. structs will have all of their parent's properties:

```bash
struct Father
    $prop_x = 100
endstruct

struct Child < Father
endstruct

$a = ^ new Child

println $a->['prop_x']
```

**Comment by sami2020pro** [comment]
I think it is too early to make such a thing, it is still not clear what exactly we want to do !

**Comment by parsampsh** [comment]
so, this feature can be added in 30 minutes and is very easy. why not?

**Comment by sami2020pro** [comment]
The best thing is to move forward **slowly** !!!

**Comment by parsampsh** [comment]
yes :) i'll close it
