### ISSUE TITLE
Site URL is incorrect

### ISSUE THREAD

**Issue by PooiaFerdowsi** [pashmaklang/pashmak#172]
The site URL in the upper right portion of the page doesn't match `http://pashmaklang.github.io/pashmak`

**Comment by PooiaFerdowsi** [comment]
in about section, the site is [pashmak-parsampsh.fandogh.cloud](https://pashmak-parsampsh.fandogh.cloud/) but it's http://pashmaklang.github.io/pashmak actually

**Comment by PooiaFerdowsi** [comment]
The online interpreter is a simple `default backend 404`

**Comment by parsampsh** [comment]
> The online interpreter is a simple `default backend 404`

I'm hosting the online interpreter on a free fandogh service. it happens all the time and i need to re-run it every time manually. so i don't host it anymore.

**Comment by PooiaFerdowsi** [comment]
so, when it doesn't work, why should you set the site to that? (in about section, upper right portion) instead of github.io?
