### ISSUE TITLE
Add pashmak to GitHub

### ISSUE THREAD

**Issue by sami2020pro** [pashmaklang/pashmak#19]
Pashmak code is increasing. We have to introduce Pashmak language to **GitHub** and write **syntax highlighter**.
Introduce Pashmak language to GitHub is **simple** and we can do it.

**Comment by parsampsh** [comment]
> Pashmak code is increasing. We have to introduce Pashmak language to **GitHub** and write **syntax highlighter**.
> Introduce Pashmak language to GitHub is **simple** and we can do it.

how can us do it?
also how to create syntax highlighter?

**Comment by Paptoos** [comment]
To add it to github , contact github , you can send a email for github

**Comment by parsampsh** [comment]
> To add it to github , contact github , you can send a email for github

Thanks! i do this

**Comment by sami2020pro** [comment]
Nice

**Comment by parsampsh** [comment]
i sent the request for github. waiting for response...

**Comment by Paptoos** [comment]
Github answered ?

**Comment by parsampsh** [comment]
yes. them said we have to add our language to https://github.com/github/linguist but before it we need syntax highlighter.

This is github full answer:


>We use the open source tool Linguist to provide language detection support on GitHub:

> https://github.com/github/linguist
>Before we can perform syntax highlighting for a language, it needs to have an open source Textmate-style language grammar. These grammars also provide syntax highlighting for the Textmate, Sublime Text, and Atom editors:
> http://manual.macromates.com/en/language_grammars
> Once you've found or created a grammar you can submit it to linguist by following this guide:
> https://github.com/github/linguist/blob/master/CONTRIBUTING.md
> Let us know if there's anything else we can do for you.
> Cheers,
> Simon
> GitHub Support

**Comment by sami2020pro** [comment]
> yes. them said we have to add our language to https://github.com/github/linguist but before it we need syntax highlighter.
> 
> This is github full answer:
> 
> 
> >We use the open source tool Linguist to provide language detection support on GitHub:
> 
> > https://github.com/github/linguist
> >Before we can perform syntax highlighting for a language, it needs to have an open source Textmate-style language grammar. These grammars also provide syntax highlighting for the Textmate, Sublime Text, and Atom editors:
> > http://manual.macromates.com/en/language_grammars
> > Once you've found or created a grammar you can submit it to linguist by following this guide:
> > https://github.com/github/linguist/blob/master/CONTRIBUTING.md
> > Let us know if there's anything else we can do for you.
> > Cheers,
> > Simon
> > GitHub Support
> 

Thats nice

**Comment by parsampsh** [comment]
so, what we have to do now?

**Comment by Paptoos** [comment]
I am sorry but my english is not very good and i write persian :
الان دو کار دارم
syntax highlighter
اضافه کردن به زبان ها
به نظرم باید اول هایلایتر رو تکمیل کنیم ( خود گیت هاب گفته

**Comment by parsampsh** [comment]
> I am sorry but my english is not very good and i write persian :
> الان دو کار دارم
> syntax highlighter
> اضافه کردن به زبان ها
> به نظرم باید اول هایلایتر رو تکمیل کنیم ( خود گیت هاب گفته

دمت گرم :)

**Comment by Paptoos** [comment]
I send request for linguist

**Comment by parsampsh** [comment]
thanks

**Comment by Paptoos** [comment]
> If the language meets the popularity requirement detailed in the CONTRIBUTING.md file, feel free to submit a PR adding support for this language. The requirement is vague at the moment, but we take 200 unique user/repos as a minimum.
the result is this 
200 user/repo is very big number

**Comment by parsampsh** [comment]
> > If the language meets the popularity requirement detailed in the CONTRIBUTING.md file, feel free to submit a PR adding support for this language. The requirement is vague at the moment, but we take 200 unique user/repos as a minimum.
> > the result is this
> 
> 200 user/repo is very big number

shit.

**Comment by parsampsh** [comment]
so, don't think about that. the first step should be creating **syntax highlighter**.

**Comment by Paptoos** [comment]
I think about we create one repo and if i can collect others to create one repo by pashmak

**Comment by sami2020pro** [comment]
Nice everybody :)

**Comment by parsampsh** [comment]
@Paptoos Please check your email.

**Comment by parsampsh** [comment]
Guys. please continue this issue in #76
