### ISSUE TITLE
Error in new feature (structures)

### ISSUE THREAD

**Issue by sami2020pro** [pashmaklang/pashmak#20]
I write this code
```html
struct Person
  $name
  $age
endstruct

$person_one = ^ new Person
$person_one->['name'] = 'Sami'
$person_one->['age'] = 14

println $person_one
```

But i get this output
```
SyntaxError: undefined operation "struct":
        in structs.pashm:1: struct Person
```

Why ?

**Comment by parsampsh** [comment]
did you updated?

**Comment by parsampsh** [comment]
i'm running it and it works correctly. please update to latest commit

**Comment by sami2020pro** [comment]
Ok

**Comment by sami2020pro** [comment]
The latest version is `v0.5.4` but no support struct !?
You release the new version ?

**Comment by parsampsh** [comment]
> The latest version is `v0.5.4` but no support struct !?
> You release the new version ?

don't use the latest version. struct is not released. use the **latest commit**

**Comment by sami2020pro** [comment]
OK, Thanks !
