### ISSUE TITLE
ready to release 0.6

### ISSUE THREAD

**Issue by parsampsh** [pashmaklang/pashmak#24]
They are the changes:

- removed `loop` and `while` functions
- created **Class** system
- change default `RuntimeError` name to the real python exception name in exception system
- created consts system
- some optimizations in mem eval parser
- added a feature to use mem symbol `^` in eval, now you can run `my_function ^ + ' something else'`
- added syntax feature to put `()` in function call syntax, for example `println("hello world")` or `my_func(1, 2)`
- some optimizations in interpreter code
- added `if..elif..else` statement

we are ready for release `0.6`. just before it, we need test more and fix detected bugs.

**Comment by Paptoos** [comment]
Yes , is good ,
I think now pashmak need a framework to create api
it is good for 0.7

**Comment by sami2020pro** [comment]
Nice
