### ISSUE TITLE
Pashmak is object-oriented

### ISSUE THREAD

**Issue by sami2020pro** [pashmaklang/pashmak#25]
I saw that classes were added to Pashmak, so I was asked if Pashmak wanted to be **object-oriented** ?
If it is **object-oriented**, it wants to be **prototype-based** or **class-based** ?
If Pashmak is **object-oriented**, why don't I see it and it is not like ***object-oriented languages*** at all, and why did you add Harrow _class_ ?

**Comment by parsampsh** [comment]
The classes are added. but I don't think we should going to be fully object-oriented.

**Comment by Paptoos** [comment]
Now pashmak is method ( function ) base

**Comment by parsampsh** [comment]
> Now pashmak is method ( function ) base

like php. php has classes, but is function base.

**Comment by sami2020pro** [comment]
> > Now pashmak is method ( function ) base
> 
> like php. php has classes, but is function base. but we also can use classes.

PHP is **Object-Oriented** programming language :/

**Comment by sami2020pro** [comment]
If you want to be **object-oriented**, apply the principle of **object-oriented**

**Comment by parsampsh** [comment]
> > > Now pashmak is method ( function ) base
> > 
> > 
> > like php. php has classes, but is function base. but we also can use classes.
> 
> PHP is **Object-Oriented** programming language :/

yes. php is oop. but i means that, a language like Python, FULLY BASED on OOP. strings, int,... and everything in python is based on oop. but in php is not like this. i think pashamk are going to be something like this.

**Comment by parsampsh** [comment]
> If you want to be **object-oriented**, apply the principle of **object-oriented**

no for now. maybe in future. but for now, its not needed.

**Comment by sami2020pro** [comment]
> > If you want to be **object-oriented**, apply the principle of **object-oriented**
> 
> no for now. maybe in future. but for now, its not needed.

OK
