### ISSUE TITLE
Function is variable

### ISSUE THREAD

**Issue by Paptoos** [pashmaklang/pashmak#26]
Pashmak can add function for var ?
or pashmak has any function in var ?
like this :
```php
$var = 'Hello World';
$var.split ' ';
```

**Comment by parsampsh** [comment]
Pashmak has all of python datatype methods.

for example:

```bash
$my_str = '    hello world    '
println $my_str->strip()
```

**Comment by Paptoos** [comment]
We can add a function for it ?

**Comment by parsampsh** [comment]
> We can add a function for it ?

no. this is handled by Python. we maybe can add it later(add own handled datatypes).

**Comment by Paptoos** [comment]
please add it to TODO
its need
thanks

**Comment by parsampsh** [comment]
hello paptoos. i checked this and tryied to make this feature. but there is some problems with python and we cannot normally add property or method to python builtin datatypes.
but there is another way.

we can create functions(if needed) as a function for doing something on strings.
for example:

```bash
$my_str = 'hello world'

func do_something_with_string ($str)
        # do something with the $str
       
        # then return new str
        mem $str
endfunc
```

i'll close this
