### ISSUE TITLE
Use uint in Pashmak

### ISSUE THREAD

**Issue by sami2020pro** [pashmaklang/pashmak#27]
How can i use **uint** in Pashmak programming language ?
I used to write a simple library for the terminal and now I want to write something else and I need to use uints naturally to use uints in _pashmak_.

**Comment by parsampsh** [comment]
Pashmak variables are FULLY HANDLED BY PYTHON. all of python datatypes are accessible.

**Comment by sami2020pro** [comment]
Nice
