### ISSUE TITLE
BUGs and Functions

### ISSUE THREAD

**Issue by sami2020pro** [pashmaklang/pashmak#28]
In new commit and version 6, **WE HAVE MANY FUNCTION BUG**, please fix all !
I stopped all my work for Pashmak because of these **bugs**.

**Comment by parsampsh** [comment]
Yes. this bug is from calling functions inside the namespaces. will be fixed soon. if there is another bug tell me.

**Comment by parsampsh** [comment]
bug was fixed.

also, if you have problem with somecode like this:

```bash
func hello
      mem 'output'
endfunc

$msg = ^ hello
```

the `$var = ^ func_or_command` syntax is deleted.

use this instead of that:

```bash
$var = %{ my_command_or_function 'arguments...' }%
```

**Comment by parsampsh** [comment]
0.6-beta2 was released.

**Comment by parsampsh** [comment]
please test it and tell me is your problem solved?
