### ISSUE TITLE
Implement Methods for Classes

### ISSUE THREAD

**Issue by sami2020pro** [pashmaklang/pashmak#29]
How can i implement **Methods** for **Classes** !?
If this does not exist, add it to **Pashmak**

**Comment by parsampsh** [comment]
you can declare methods for classes like this example:

```bash
class Something
    $name = 'someone'

    func say_hi
        println 'hello. my name is ' + $this->name
    endfunc
endclass
```

read the doc for more https://github.com/pashmaklang/pashmak/#class-methods
