### ISSUE TITLE
Import one func or all

### ISSUE THREAD

**Issue by Paptoos** [pashmaklang/pashmak#30]
I read the fully documentation and i have many ideas 
I do not find this in python to pashmak :
```python
from sys import argv
# or
from sys import *
```
what is this in pashmak
I know we can use python code but i think if you handle it , it is better

**Comment by parsampsh** [comment]
normally, when we want to import a module, all of that will be imported.

for example:

```bash
import @sys
```

and actually structure of interpreter is different and cannot accept this feature.
actually, the `import` command is not like python, and is like `include` and `include_once` php functions.

if you want to load a sub namespace from a module, you can use `use` command:

```bash
import @sys
use sys.path
println %{ list }% # instead of sys.path.list
```

**Comment by Paptoos** [comment]
I think it is up the size of program
I closed , but if you can add it (:
Thanks
