### ISSUE TITLE
Web Framework

### ISSUE THREAD

**Issue by hasan-kashi** [pashmaklang/pashmak#32]
Hi.
You can create a web framework for back-end development with pashmak, you can customize Django or Flask and put it in Pashmak programming language.

**Comment by parsampsh** [comment]
Hello hasan. Pashmak is in the first of road. First, we need to make ready a stable release of pashmak interpreter. then we can go to build something like this.

**Comment by hasan-kashi** [comment]
OK.
I will try to write a small web framework for pashmak.
Please do not close this issue until it is completed.

**Comment by parsampsh** [comment]
Hi hasan. if you are working on this, make sure to use 0.6-beta6 release. Also, if your project needs a python standard library, tell me to import that in interpreter in next releases. Thanks.

**Comment by sami2020pro** [comment]
Wait, It's too early to make such a thing.

**Comment by Paptoos** [comment]
No , pashmak now is good and if start using it , bugs can find .

**Comment by parsampsh** [comment]
Yes. It also helps us to find bugs.

**Comment by parsampsh** [comment]
Yes. It also helps us to find bugs.

**Comment by parsampsh** [comment]
Hi hasan. Is this project running? If yes, has any repo on github? If this is available on github, give link to me. Maybe I can contribute to that :)

**Comment by hasan-kashi** [comment]
Hi. I am currently building a server for pashmak web framework.
If you want to help, write a module for working with html for Pashmak

**Comment by parsampsh** [comment]
> Hi. I am currently building a server for pashmak web framework.
> If you want to help, write a module for working with html for Pashmak

Working with html? The web framework is used to handle backend. Why you need to work with html in that? your framework can send the html as a text to the client. ?

**Comment by hasan-kashi** [comment]
pashmak web framework works like the following code :
```
<!DOCTYPE html>
{$title = 'The Pashmak Web Framework' }
<html>
<body>
 <h1>{$title}</h1>
{println('<p>test</p>') }
</body>
</html>
```

**Comment by Paptoos** [comment]
@parsampsh it is **not** a **api framework** , it is a **web framework** .

@hasan-kashi it is very good .

**Comment by parsampsh** [comment]
> pashmak web framework works like the following code :
> 
> ```
> <!DOCTYPE html>
> {$title = 'The Pashmak Web Framework' }
> <html>
> <body>
>  <h1>{$title}</h1>
> {println('<p>test</p>') }
> </body>
> </html>
> ```

Oh yes. I thought this is just a api framework. It's something like blade and jinja.
OK. I'll try.(maybe using a python library).

**Comment by parsampsh** [comment]
I suggest something like this:

```
...
<div>
...
{{ println('something') }}
...
{(= $somevar }}
</div>
...
```

`{{ <code> }}` for running the code inside the html.
and `{{= <something> }}` to show something as a value(variable or result of function).

**Comment by parsampsh** [comment]
What is your say guys?

> I suggest something like this:
> 
> ```
> ...
> <div>
> ...
> {{ println('something') }}
> ...
> {(= $somevar }}
> </div>
> ...
> ```
> 
> `{{ <code> }}` for running the code inside the html.
> and `{{= <something> }}` to show something as a value(variable or result of function).

**Comment by Paptoos** [comment]
one `{ <code> }` is better , because it is easier than two `{{ <code> }}`

and using ` = ` have other means in pashmak  and it is not good . I think `{ $somevar } ` or ` { ^$somevar } `

**Comment by parsampsh** [comment]
> one `{ <code> }` is better , because it is easier than two `{{ <code> }}`
> 
> and using `=` have other means in pashmak and it is not good . I think `{ $somevar } ` or `{ ^$somevar }`

So we need a way to diagnose them. for example in php `<?php ?>` and `<?= ?>` are diffrents.

**Comment by parsampsh** [comment]
For example `{ <code> }` for first
and `{= $somevar }` OR `{^ $somevar}`.

**Comment by Paptoos** [comment]
`{ $somevar } ` is not good ?

**Comment by parsampsh** [comment]
> `{ $somevar } ` is not good ?

We have two types: Variable showing, Code running.

We can use `{ }` for one of them. for example `{ code }` for running code and `{= $var }` for showing vars.
like php. in php we cannot run `<?php $var ?>`. `<?php ?>` is for running code and `<?= $var ?>` is for showing a variable/value.

**Comment by Paptoos** [comment]
Yes , I have other idea now : ` { $code } {{ $somevar }} `/

**Comment by parsampsh** [comment]
> Yes , I have other idea now : `{ $code } {{ $somevar }}`/

Yes this is so good. :)

**Comment by parsampsh** [comment]
OK. I'll try to write this.

**Comment by parsampsh** [comment]
I wrote a basic in https://github.com/pashmaklang/pashm-html

**Comment by Paptoos** [comment]
It is very good ,

**Comment by hasan-kashi** [comment]
One tip: we need to make this module start working when the user logs in to the site. Leave it to me.

**Comment by parsampsh** [comment]
@hasan-kashi Do you need to import any python standard library for your framework? For example `socket`? If you want i can import this in pashmak to be accessible in pashmak.

**Comment by hasan-kashi** [comment]
> 
> 
> @hasan-kashi Do you need to import any python standard library for your framework? For example `socket`? If you want i can import this in pashmak to be accessible in pashmak.

`http`

**Comment by parsampsh** [comment]
Ok. I'll add it.

**Comment by parsampsh** [comment]
Added.

**Comment by parsampsh** [comment]
Hello @hasan-kashi
I wrote a internal module named `webserver`. This can serve the http server. This maybe helpful for your project.
Doc: https://github.com/pashmaklang/pashmak/blob/master/doc/10_modules/07_webserver.md

**Comment by hasan-kashi** [comment]
Thanks. I had a lot of problems with the Python web server and its connection to pashmak.I will continue to work with this module.

**Comment by sami2020pro** [comment]
I think this is too early for **Pashmak** and I have to do other things, for example, we do not have a  ___library___ for ___cookies___.

**Comment by parsampsh** [comment]
> I think this is too early for **Pashmak** and I have to do other things, for example, we do not have a _**library**_ for _**cookies**_.

So, the web framework should have this :) Also, the `webserver` builtin module using python's http server request handler, this contains a feature for working with cookies.

**Comment by sami2020pro** [comment]
> > I think this is too early for **Pashmak** and I have to do other things, for example, we do not have a _**library**_ for _**cookies**_.
> 
> So, the web framework should have this :) Also, the `webserver` builtin module using python's http server request handler, this contains a feature for working with cookies.

This is too small and enough for now, we will work better later.

**Comment by parsampsh** [comment]
I moved `pashm-html` to Pashmak's interpreter as a internal module, also i ranamed it to `T-Engine`.
read the doc: https://github.com/pashmaklang/pashmak/blob/master/doc/11_advance/06_tengine.md

**Comment by parsampsh** [comment]
Hi guys. I'm writing base of web development features for Pashmak to run it behind a web server and on the backend with HTTP.
This is in progress in this branch: https://github.com/pashmaklang/pashmak/tree/feature/add-runnable-script-for-webserver-module

**Comment by parsampsh** [comment]
I wrote a builtin web development system. Read the doc here: https://github.com/pashmaklang/pashmak/tree/master/doc/12_web
If you wanna make a web framework, you can create that based on this system.
I'll close this issue.
