### ISSUE TITLE
use python modules

### ISSUE THREAD

**Issue by hasan-kashi** [pashmaklang/pashmak#35]
Hi.
add importing python modules in pashmak.
for example :
`import 'module.py'`

**Comment by parsampsh** [comment]
Ok. I think this is possible. I'll think about that.

**Comment by parsampsh** [comment]
I created it in branch [create-pyloadfile-function](https://github.com/pashmaklang/pashmak/tree/create-pyloadfile-function).
read the doc here: https://github.com/pashmaklang/pashmak/tree/create-pyloadfile-function#py_load_file
Please test it and tell me the result, then I merge it into master.

**Comment by parsampsh** [comment]
I merged it into master.
