### ISSUE TITLE
json usage

### ISSUE THREAD

**Issue by Paptoos** [pashmaklang/pashmak#36]
I read the pashmak full documentation . but i do not find usage json . 
pashmak have a json library ? ( if not please write one , you can use json python library )

**Comment by parsampsh** [comment]
Hi. I'll import Python json module in next release

**Comment by parsampsh** [comment]
Added.

example:

```python
$data = {'foo': 'bar', 'hoho': [1, 2, 3]}
$json = json.dumps($data)
println($json)
```

output:

```
{"foo": "bar", "hoho": [1, 2, 3]}
```

**Comment by Paptoos** [comment]
Thanks
