### ISSUE TITLE
Cannot run this programming language in exe application

### ISSUE THREAD

**Issue by mehanalavimajd** [pashmaklang/pashmak#40]
I am using windows 10 . 
I use the introductions that you have put it in the README.md.
I clone the project and did all of the things that you have said.
After that I had .exe file in dist directory but it was very heavy about 8 mg !!!! 
It was only a hello world application.
When I open the .exe file it will open a black window
And after that it write something in the window and then It will be closed .
Please solve this problem very soon.

**Comment by Paptoos** [comment]
Hello , you must be clone and after using pyinstaller change app to a `.exe` file , your programs do not have exe file . for testing the `exe` file using this command :

```bash
/path/pashmak.exe -v
```

if it is not work test the python file .

**Comment by parsampsh** [comment]
Yes. I think the pyinstaller does not puts `.exe` extension by default. You should add `.exe`. Also, do not run the file by executing it by file manager/double click/gui... You should run it from terminal Like that thing Paptoos said.

**Comment by mehanalavimajd** [comment]
Ok , but the application file was very heavy 
Please do something about app weight

**Comment by parsampsh** [comment]
> Ok , but the application file was very heavy
> Please do something about app weight

In the GNU/Linux app binary size is 5.5MB and Myself don't have any problem with that :) But another option is that to running this without compiling.

**Comment by mehanalavimajd** [comment]
Yes I think that running without compiling is best way.thanks very much
