### ISSUE TITLE
Bug in classes

### ISSUE THREAD

**Issue by Paptoos** [pashmaklang/pashmak#41]
I Testing a code to find bug from pashmak and I can .
I run this code :
```bash
class T
    func E
        class S
            $somevar = " Testing "
        endclass
        $T = S()
        println($T=>$somevar)
    endfunc
endclass
$K = T()
$K=>E()
```
and i get this error : 
```
NameError: name 'S' is not defined:
	in /tmp/temp-script-1609183110899348940.pashm:6: $T = S()
```
I using the online interpreter .

**Comment by parsampsh** [comment]
Why you used `=>`? `->` is valid :)
And declaring class-in-class or in function is not possible.(Maybe added for later) :)

**Comment by Paptoos** [comment]
> Why you used =>? -> is valid :)

I am forget , but error is not from that

**Comment by Paptoos** [comment]
> And declaring class-in-class or in function is not possible.(Maybe added for later) :)

It is need

**Comment by parsampsh** [comment]
Yes. I'll add it to todo.

**Comment by parsampsh** [comment]
Added.

Read the docs:
https://github.com/pashmaklang/pashmak#complicated-function-declaration
https://github.com/pashmaklang/pashmak#complicated-class-declaration
