### ISSUE TITLE
how to make changes in modules in windows?

### ISSUE THREAD

**Issue by mehanalavimajd** [pashmaklang/pashmak#44]
I'm using windows 10.I have made a change in modules directory (added os.mkdir function) and I want to know how does it works.
You have wrote in CONTRIBUTING.md that you have to use `make module`  see how does your change will work but I can't use this command (I mean `make module`) so how can I make changes in modules in windows?

**Comment by parsampsh** [comment]
You should use `win-configure.bat` script in windows:

```bash
.\win-configure.bat
```

This script builds modules.

**Comment by mehanalavimajd** [comment]
Thanks
