### ISSUE TITLE
Random moudle

### ISSUE THREAD

**Issue by Paptoos** [pashmaklang/pashmak#48]
Hi
I complete random module but choice functions have bug and do not work , @parsampsh can you help ?
the source code of this function :
```
func choice($args)
    python("self.mem = random.choice(self.get_var('args')[0]")
endfunc
```
the test code : 
```
import @random
$a = ["Hello" , "Hello2" , "Hello3" , "Hello4"]
random.choice($a)
print(^)
```
and error : 
```
SyntaxError: unexpected EOF while parsing (<string>, line 1):
        in test.pashm:3: random.choice ($a)
        in @random:21: python ("self.mem = random.choice(self.get_var('args')[0]")
        in @stdlib:62: rmem exec(^)
```

**Comment by parsampsh** [comment]
Yes. looks has problem. I'll fix it.

**Comment by parsampsh** [comment]
Shit :). that was a syntax error. you forget to write a `)` :).

This works:

```bash
namespace random
    func choice($args)
        python("self.mem = random.choice(self.get_var('args'))")
    endfunc
endns

$a = ["Hello" , "Hello2" , "Hello3" , "Hello4"]
println random.choice($a)

```

**Comment by Paptoos** [comment]
Thanks , I fix it

**Comment by Paptoos** [comment]
It has other bug (:
it is change array type to string and return one char of string

**Comment by parsampsh** [comment]
Yes. Actually, if you pass more than 1 argument to function, pashmak puts that as array in `$args`. but if you only pass 1 argument to function, that is not array and is even that variable in `$args`.

for example:

```bash
func hello($args)
    println($args)
endfunc

hello(10) # output: 10
hello(10, 11) # output: [[10, 11]
```

**Comment by Paptoos** [comment]
Yes , but when we pass a array , pashmak should be send it in `$args` array .
if pashmak can not , i can't create choice function

**Comment by parsampsh** [comment]
You should remove `[0]`

convert

```bash
python("self.mem = random.choice(self.get_var('args')[0])")
```

to

```bash
python("self.mem = random.choice(self.get_var('args'))")
```

**Comment by Paptoos** [comment]
Thanks
