### ISSUE TITLE
Ready to release 0.6

### ISSUE THREAD

**Issue by parsampsh** [pashmaklang/pashmak#56]
Now, all of needed features are added, lot of optimizations done, and lot of bugs are fixed. We are ready to release 0.6. Now we are on pre release `0.6-rc4`. We should more test, and fix detected bugs, then release 0.6. please test this and if there is any bug, tell me to fix it.

Thnaks!

**Comment by mehanalavimajd** [comment]
Can we wain a little bit to release the 0.6 because I want to create math module

**Comment by parsampsh** [comment]
> Can we wain a little bit to release the 0.6 because I want to create math module

Yes of course. I'll wait for your PR before release.

**Comment by Paptoos** [comment]
I start the testing

**Comment by parsampsh** [comment]
Released.
