### ISSUE TITLE
Function argument limit

### ISSUE THREAD

**Issue by sami2020pro** [pashmaklang/pashmak#74]
I was not there for a while and I was not in the process of development and I have to apologize.
In connection with the logo, I am also doing standard libraries.

I found a problem and my question is why it is not possible to give a few variables to a function in Pashmak if you can please fix this bug ?!

**Comment by parsampsh** [comment]
Hello. Thank you for working on logo and libraries. About the function arguments, read the doc here: https://github.com/pashmaklang/pashmak/blob/master/doc/02_functions/04_formating_arguments.md
You can call this a problem but i call this a feature :)

**Comment by mehanalavimajd** [comment]
@sami2020pro can you make the logo faster please beacuse I need it for creating website

**Comment by sami2020pro** [comment]
> Hello. Thank you for working on logo and libraries. About the function arguments, read the doc here: https://github.com/pashmaklang/pashmak/blob/master/doc/02_functions/04_formating_arguments.md
> You can call this a problem but i call this a feature :)

Thanks \_(--)_/

**Comment by sami2020pro** [comment]
> @sami2020pro can you make the logo faster please beacuse I need it for creating website

I designed a few logos but did not know which one was right for Pashmak.
I suggest two types of logos:

1. Shape
2. Text

Which one did you prefer ?

**Comment by sami2020pro** [comment]
> Hello. Thank you for working on logo and libraries. About the function arguments, read the doc here: https://github.com/pashmaklang/pashmak/blob/master/doc/02_functions/04_formating_arguments.md
> You can call this a problem but i call this a feature :)

In my opinion, this is not a good feature and it is problematic

**Comment by mehanalavimajd** [comment]
> > @sami2020pro can you make the logo faster please beacuse I need it for creating website
> 
> I designed a few logos but did not know which one was right for Pashmak.
> I suggest two types of logos:
> 
> 1. Shape
> 2. Text
> 
> Which one did you prefer ?

I think shape is better

**Comment by sami2020pro** [comment]
> > > @sami2020pro can you make the logo faster please beacuse I need it for creating website
> > 
> > 
> > I designed a few logos but did not know which one was right for Pashmak.
> > I suggest two types of logos:
> > 
> > 1. Shape
> > 2. Text
> > 
> > Which one did you prefer ?
> 
> I think shape is better

I can't think of a way you have an idea or to use things that have Pashmak, for example, what is strong in you or what color is the official color of Pashmak.

**Comment by sami2020pro** [comment]
> Hello. Thank you for working on logo and libraries. About the function arguments, read the doc here: https://github.com/pashmaklang/pashmak/blob/master/doc/02_functions/04_formating_arguments.md
> You can call this a problem but i call this a feature :)

Write a sum function with this feature :)

**Comment by parsampsh** [comment]
> > Hello. Thank you for working on logo and libraries. About the function arguments, read the doc here: https://github.com/pashmaklang/pashmak/blob/master/doc/02_functions/04_formating_arguments.md
> > You can call this a problem but i call this a feature :)
> 
> Write a sum function with this feature :)

```bash
func sum($args)
    $args = format_args($args)
    return $args[0] + $args[1]
endfunc

println(sum(5, 10)) # 15
```

**Comment by sami2020pro** [comment]
> > > Hello. Thank you for working on logo and libraries. About the function arguments, read the doc here: https://github.com/pashmaklang/pashmak/blob/master/doc/02_functions/04_formating_arguments.md
> > > You can call this a problem but i call this a feature :)
> > 
> > 
> > Write a sum function with this feature :)
> 
> ```shell
> func sum($args)
>     $args = format_args($args)
>     return $args[0] + $args[1]
> endfunc
> 
> println(sum(5, 10)) # 15
> ```

Interestingly, I was not careful |--|

**Comment by sami2020pro** [comment]
@parsampsh 
OK, I created a logo in Krita but i have a small problem, What color is the **official color** of Pashmak programming language?
I will send  this image to you.

**Comment by parsampsh** [comment]
> @parsampsh
> OK, I created a logo in Krita but i have a small problem, What color is the **official color** of Pashmak programming language?
> I will send this image to you.

Thank you so much!
Choose the color yourself :)

**Comment by sami2020pro** [comment]
> > @parsampsh
> > OK, I created a logo in Krita but i have a small problem, What color is the **official color** of Pashmak programming language?
> > I will send this image to you.
> 
> Thank you so much!
> Choose the color yourself :)

I made five logos with different colors, I will probably send logos with **Email** or **Signal**.
If you do not find a good color between these five and you do not like, send me the approved color of Pashmak as a hex to change it. If you do not even like the logo, tell me to change it.
you have signal?

**Comment by parsampsh** [comment]
> > > @parsampsh
> > > OK, I created a logo in Krita but i have a small problem, What color is the **official color** of Pashmak programming language?
> > > I will send this image to you.
> > 
> > 
> > Thank you so much!
> > Choose the color yourself :)
> 
> I made five logos with different colors, I will probably send logos with **Email** or **Signal**. (Sent)
> If you do not find a good color between these five and you do not like, send me the approved color of Pashmak as a hex to change it. If you do not even like the logo, tell me to change it.
> you have signal?

Thank you so much sami. no, i haven't signal. can you send it to my email or my telegram https://t.me/parsampsh ?

**Comment by parsampsh** [comment]
I recived it. please continue this issue in #11

**Comment by parsampsh** [comment]
@sami2020pro Now this feature is added. You can declare more than one variable and you don't need to use `format_args`.

```bash
func hello($name, $family='default') # also you can set default values for arguments
    println('Hello ' + $name + ' ' + $family)
endfunc
```

also you can set type of arguments:

```bash
func hello(str $name, int $age, bool $something=True)
    # ...
endfunc
```

also you can use named arguments(keyword arguments):

```bash
some_func('a', 'b', something='c')
```

This feature is added in GH-95

**Comment by sami2020pro** [comment]
> @sami2020pro Now this feature is added. You can declare more than one variable and you don't need to use `format_args`.
> 
> ```bash
> func hello($name, $family='default') # also you can set default values for arguments
>     println('Hello ' + $name + ' ' + $family)
> endfunc
> ```
> 
> also you can set type of arguments:
> 
> ```bash
> func hello(str $name, int $age, bool $something=True)
>     # ...
> endfunc
> ```
> 
> also you can use named arguments(keyword arguments):
> 
> ```bash
> some_func('a', 'b', something='c')
> ```
> 
> This feature is added in GH-95
> 
> (It's new and maybe have bug).
> 
> also the old strategy is already available:
> 
> ```bash
> func hello(*$args)
>     println $args[0] + $args[1]
> endfunc
> ```

Nice features, i wanna update my repo and libraries.

**Comment by parsampsh** [comment]
Also https://github.com/pashmaklang/pashmak/blob/master/doc/02_functions/00_functions.md#advance-typed-arguments added. for example:

```bash
func hello(int|str $a)
    #
endfunc
```

or:

```
int|list
list[int]
list[int|str]
list[str|list[bool|str]]
...
```
