### ISSUE TITLE
Suit IDE

### ISSUE THREAD

**Issue by momhiar** [pashmaklang/pashmak#76]
Hi there, pashmak is good in some cases and now is stable enough to make an IDE  or at least a plugin for VS code .
Anyway , i am trying to make a primary IDE for pashmak Development :)
Good luck .

**Comment by mehanalavimajd** [comment]
Thanks

**Comment by mehanalavimajd** [comment]
Thanks

**Comment by parsampsh** [comment]
Great! Thanks!

**Comment by sami2020pro** [comment]
I am writing a vscode extension with **TypeScript** and I will let you know :)

**Comment by momhiar** [comment]
> I am writing a vscode extension with **TypeScript** and I will let you know :)

-ok , i was trying to make an IDE not an Extension , anyway  , I'll start soon

**Comment by sami2020pro** [comment]
I just started to create an extension for **Visual Studio Code** [here](https://github.com/sami2020pro/vscode-pashmak) :tumbler_glass:
@parsampsh

**Comment by mehanalavimajd** [comment]
Can you publish it vscode?

**Comment by parsampsh** [comment]
> I start create an extension for **Visual Studio Code** [here](https://github.com/sami2020pro/vscode-pashmak) tumbler_glass
> @parsampsh

This is a great boy! I look forward to it!

**Comment by parsampsh** [comment]
> Can you publish it vscode?

For testing it only clone the repo in `~/.vscode/extensions` and run the vscode.

**Comment by parsampsh** [comment]
> I start create an extension for **Visual Studio Code** [here](https://github.com/sami2020pro/vscode-pashmak) tumbler_glass
> @parsampsh

I don't know about structure of vscode extension, but maybe i read about and contribute.

**Comment by parsampsh** [comment]
I published the vscode extension to vscode marketplace. now you can install it from extensions section. only search `pashmak`.

**Comment by mehanalavimajd** [comment]
How did  you publish it ?
I want to know how to pubish extention in vscode .

**Comment by parsampsh** [comment]
> How did you publish it ?
> I want to know how to pubish extention in vscode .

You should go to the marketplace.visualstudio.com and sign up and then publish your package (`.VSIX`)
Also you can use `vsce` command line tool to publish your package from command line(`sudo npm install --global vsce`).
[Read the official documentation](https://code.visualstudio.com/api/working-with-extensions/publishing-extension).

**Comment by mehanalavimajd** [comment]
> > How did you publish it ?
> > I want to know how to pubish extention in vscode .
> 
> You should go to the marketplace.visualstudio.com and sign up and then publish your package (`.VSIX`)
> Also you can use `vsce` command line tool to publish your package from command line(`sudo npm install --global vsce`).
> [Read the official documentation](https://code.visualstudio.com/api/working-with-extensions/publishing-extension).

Thanks.

**Comment by mehanalavimajd** [comment]
I think we have to add a text editor with the sourse code . Like the idle in python

**Comment by mehanalavimajd** [comment]
I think we can put a text editor like idle in pashmak pack.

**Comment by parsampsh** [comment]
> I think we can put a text editor like idle in pashmak pack.

I don't know enough about GUI programming. others can make an external app.

**Comment by mehanalavimajd** [comment]
> > I think we can put a text editor like idle in pashmak pack.
> 
> I don't know enough about GUI programming. others can make an external app.

Thinker or pyQT or even electron.js are good choices.
If a had the electron knowlage i would do it but i dont kniow it

**Comment by parsampsh** [comment]
> > > I think we can put a text editor like idle in pashmak pack.
> > 
> > 
> > I don't know enough about GUI programming. others can make an external app.
> 
> Thinker or pyQT or even electron.js are good choices. If a had the electron knowledge i would do it but i dont know it

I don't know too =) But anyway we've got a VSCode extension. I think we don't need a IDE. we can just improve the VSCode extension.

**Comment by sami2020pro** [comment]
Hi, I wasn't available for a while.

It's a long time since I didn't update the extension. If there are any syntax changes, let me know to update the extension.

**Comment by mehanalavimajd** [comment]
Hey @parsampsh, are you still maintaining the pashmak?

**Comment by parsampsh** [comment]
@mehanalavimajd Hi man. Yes I'm supposed to be :) But unfortunately I've been very busy with work stuff on a project and haven't had time to do things on Pashmak :( When I finish that project, I'll start development on Pashmak again.
