### ISSUE TITLE
snake_case or camelCase in pashmak

### ISSUE THREAD

**Issue by sami2020pro** [pashmaklang/pashmak#81]
**Style Guide** is important section in programming and we need to use that.
My question is when is **Style Guide** written and Pashmak wants to continue as ***snake_case*** or ***camelCase***?
I suggest ***snake_case*** because __Python__, __Rust__, etc... use ***snake_case*** and it's beautiful and amazing!

**Comment by parsampsh** [comment]
Actually, i suggest **snake_case** for functions/methods and **PascalCase** for class/namespace

**Comment by parsampsh** [comment]
I think this is good idea to add a `style guide` to the `advance` section of the documentation. what's your say?

**Comment by sami2020pro** [comment]
> Actually, i suggest **snake_case** for functions/methods and **PascalCase** for class/namespace

I hope it fits.

**Comment by sami2020pro** [comment]
> I think this is good idea to add a `style guide` to the `advance` section of the documentation. what's your say?

for ***Documents*** and ***Style Guide*** create another **repo** in __Organizations__, I think this better than other ways.

**Comment by parsampsh** [comment]
> > I think this is good idea to add a `style guide` to the `advance` section of the documentation. what's your say?
> 
> for _**Documents**_ and _**Style Guide**_ create another **repo** in **Organizations**, I think this better than other ways.

I'll add it to the main repo for now. MAYBE i split the documentation and main repo in the future.

**Comment by sami2020pro** [comment]
I think this is a good thing too.

**Comment by parsampsh** [comment]
I added it to `doc/11_advance/05_style_guide.md`.
