### ISSUE TITLE
Writing libraries in pure Python

### ISSUE THREAD

**Issue by sami2020pro** [pashmaklang/pashmak#87]
There are a series of libraries that should be written entirely in Python and it is not possible to write in Pashmak like Ruby and Python themselves, a series of libraries of which are written in **C**.
This may or may not be provided!?

**Comment by mehanalavimajd** [comment]
Can you say an example?

**Comment by sami2020pro** [comment]
> Can you say an example?

audioop and array writed in C

**Comment by sami2020pro** [comment]
Most language libraries should be written in Python itself, and higher libraries in Pashmak are more accurate.
Look at the standard libraries now. In general, they are all written with python("") for larger libraries, which can not be done.

**Comment by parsampsh** [comment]
Pashmak interpreter is very depended to the Python. We only can work in python's frame currently.

**Comment by sami2020pro** [comment]
> Pashmak interpreter is very depended to the Python. We only can work in python's frame currently.

I know but module written in pashmak file we need to change python file

**Comment by parsampsh** [comment]
Actually, the subject is that we can write lot of standard libraries fully in Pashmak from zero. For example, The `json` module. But this maybe hard. Also why when we can bind Python's json module we write this? For now, we can use python modules and use `python()` function. but in the future, we can slowly get down our dependencies to Python and write lot of modules FULLY in the Pashmak,
